choco install nvm -y
choco install firefox -y
choco install googlechrome -y
choco install powertoys -y
choco install steam-client -y
choco install spotify -y
choco install thunderbird -y
choco install discord -y
choco install obsidian -y
choco install whatsapp -y
choco install telegram -y
choco install dropbox -y
choco install slack -y
choco install razer-synapse-3 -y
choco install 7zip -y
choco install robo3t -y
choco install vscode -y
choco install qbittorrent -y
choco install screentogif.install -y
choco install paint.net -y
choco install treesizefree -y
choco install adobereader -y
choco install vlc -y
choco install git.install -y
choco install notepadplusplus.install -y
choco install nvidia-display-driver -y